### ISSUE TITLE
Cache invalidation issue

### ISSUE THREAD

**Issue by Michael77** [gustavnikolaj/express-autoprefixer#12]
The problem I am having is that my other files are not being cached by the browser when this middleware is enabled, but when I am not using this module the images and javascript etc. are being cached again(304 not modified).

Here is the relevant code I am using to configure express:

`const app = express();`
`app.set( 'port', process.env.PORT || 3000 );`
`app.use( bodyParser.urlencoded({ extended: true }) );`
`app.use( compression({ level: 9 }) );`
`app.use( autoprefixer({ browsers: 'last 3 versions', cascade: false, remove: false }) );`
`app.use( express.static( path.join(__dirname, 'public') ) );``

Using express@4.13.4

**Comment by Michael77** [comment]
Hey there, I managed to fix the problem for myself by changing line 13 of autoprefixer.js to:
`if (ifNoneMatch && fileType == ".css") {`
This allowed the prefixing and caching of css files to continue happening like before, but enabled non-css files to be cached by the browser and get 304's.

**Comment by gustavnikolaj** [comment]
You're pretty close :-) I haven't fixed the problem yet, but the problem is indeed that autoprefixer is messing with your if-none-match headers.

We need to remove them, if we didn't set the etag ourselves, as we otherwise would not be able to autoprefix files that you had already cached.  When the static middleware returns a 304 it doesn't stream the file to you, obviously, so we have to prevent that.

It's unfortunate that it makes all your files non 304-able but it's better than the alternative. I'm leaving for a little vacation over easter soon, so I won't have time to dig into it now, but if you do something like the following example, you should be able to cache everything not .css :-)

```js
app.use(function (req, res, next) {
    if (/\.css$/.test(req.originalUrl)) {
        return autoprefixer({ browsers: 'Chrome > 30', cascade: false })(req, res, next);
    }
    return next();
});
```

I'm hesitant to land that in the middleware, as I use it myself for .less files too :-)

I'll try looking at a proper fix in a weeks time.

**Comment by Michael77** [comment]
Thanks for the solution and enjoy your vacation! :D

**Comment by gustavnikolaj** [comment]
@Michael77 Thanks! :-)

The PR referenced above contains a proper fix, and is contained in the latest release of v5 (v5.0.1) and in v4.0.7 too (v4 is if you still need to run autoprefixer in version 5 for node 0.10 compatibility. :-)

Sorry for the inconvenience! Please do try it out, and report back here if it does not solve your problem :-)

**Comment by Michael77** [comment]
Awesome work man, thanks a lot!
